(function(){ var x = 1, y = 2, z = 3 });
var x = 1, y = 2, z = 3;
(function(){ { var x = 1, y = 2, z = 3 } });
(function(){ var x, y, z });
var x, y, z;
(function(){ { var x, y, z } });
(function(){ function foo() { } });
function foo() { };
(function(){ { function foo() { } } });
(function(){ function foo() { return 42 } });
function foo() { return 42 };
(function(){ { function foo() { return 42 } } });
(function(){ function f(a) { function a() { } } });
function f(a) { function a() { } };
(function(){ { function f(a) { function a() { } } } });
(function(){ function f(a,b,c) { function b() { } } });
function f(a,b,c) { function b() { } };
(function(){ { function f(a,b,c) { function b() { } } } });
(function(){ true });
true;
(function(){ { true } });
(function(){ false });
false;
(function(){ { false } });
(function(){ 42 });
42;
(function(){ { 42 } });
(function(){ (/asdf/) });
(/asdf/);
(function(){ { (/asdf/) } });
(function(){ this });
this;
(function(){ { this } });
(function(){ foo });
foo;
(function(){ { foo } });
(function(){ foo.bar });
foo.bar;
(function(){ { foo.bar } });
(function(){ foo[bar] });
foo[bar];
(function(){ { foo[bar] } });
(function(){ (function(){}) });
(function(){});
(function(){ { (function(){}) } });
(function(){ (function f() {}) });
(function f() {});
(function(){ { (function f() {}) } });
(function(){ (function f(x,y,z) {}) });
(function f(x,y,z) {});
(function(){ { (function f(x,y,z) {}) } });
(function(){ (++x) });
(++x);
(function(){ { (++x) } });
(function(){ (x++) });
(x++);
(function(){ { (x++) } });
(function(){ (+x) });
(+x);
(function(){ { (+x) } });
(function(){ (-x) });
(-x);
(function(){ { (-x) } });
(function(){ (!x) });
(!x);
(function(){ { (!x) } });
(function(){ (~x) });
(~x);
(function(){ { (~x) } });
(function(){ (delete x) });
(delete x);
(function(){ { (delete x) } });
(function(){ (typeof x) });
(typeof x);
(function(){ { (typeof x) } });
(function(){ (void x) });
(void x);
(function(){ { (void x) } });
(function(){ (x == y) });
(x == y);
(function(){ { (x == y) } });
(function(){ (x != y) });
(x != y);
(function(){ { (x != y) } });
(function(){ (x === y) });
(x === y);
(function(){ { (x === y) } });
(function(){ (x !== y) });
(x !== y);
(function(){ { (x !== y) } });
(function(){ (x < y) });
(x < y);
(function(){ { (x < y) } });
(function(){ (x <= y) });
(x <= y);
(function(){ { (x <= y) } });
(function(){ (x > y) });
(x > y);
(function(){ { (x > y) } });
(function(){ (x >= y) });
(x >= y);
(function(){ { (x >= y) } });
(function(){ (x << y) });
(x << y);
(function(){ { (x << y) } });
(function(){ (x >> y) });
(x >> y);
(function(){ { (x >> y) } });
(function(){ (x >>> y) });
(x >>> y);
(function(){ { (x >>> y) } });
(function(){ (x + y) });
(x + y);
(function(){ { (x + y) } });
(function(){ (w + x + y + z) });
(w + x + y + z);
(function(){ { (w + x + y + z) } });
(function(){ (x - y) });
(x - y);
(function(){ { (x - y) } });
(function(){ (w - x - y - z) });
(w - x - y - z);
(function(){ { (w - x - y - z) } });
(function(){ (x * y) });
(x * y);
(function(){ { (x * y) } });
(function(){ (x / y) });
(x / y);
(function(){ { (x / y) } });
(function(){ (x % y) });
(x % y);
(function(){ { (x % y) } });
(function(){ (x | y) });
(x | y);
(function(){ { (x | y) } });
(function(){ (x ^ y) });
(x ^ y);
(function(){ { (x ^ y) } });
(function(){ (x & y) });
(x & y);
(function(){ { (x & y) } });
(function(){ (x in y) });
(x in y);
(function(){ { (x in y) } });
(function(){ (x instanceof y) });
(x instanceof y);
(function(){ { (x instanceof y) } });
(function(){ (x = y) });
(x = y);
(function(){ { (x = y) } });
(function(){ (x += y) });
(x += y);
(function(){ { (x += y) } });
(function(){ (x -= y) });
(x -= y);
(function(){ { (x -= y) } });
(function(){ (x *= y) });
(x *= y);
(function(){ { (x *= y) } });
(function(){ (x /= y) });
(x /= y);
(function(){ { (x /= y) } });
(function(){ (x %= y) });
(x %= y);
(function(){ { (x %= y) } });
(function(){ (x <<= y) });
(x <<= y);
(function(){ { (x <<= y) } });
(function(){ (x >>= y) });
(x >>= y);
(function(){ { (x >>= y) } });
(function(){ (x >>>= y) });
(x >>>= y);
(function(){ { (x >>>= y) } });
(function(){ (x |= y) });
(x |= y);
(function(){ { (x |= y) } });
(function(){ (x ^= y) });
(x ^= y);
(function(){ { (x ^= y) } });
(function(){ (x &= y) });
(x &= y);
(function(){ { (x &= y) } });
(function(){ (x || y) });
(x || y);
(function(){ { (x || y) } });
(function(){ (x && y) });
(x && y);
(function(){ { (x && y) } });
(function(){ (w || x || y || z) });
(w || x || y || z);
(function(){ { (w || x || y || z) } });
(function(){ (x ? y : z) });
(x ? y : z);
(function(){ { (x ? y : z) } });
(function(){ (x,y) });
(x,y);
(function(){ { (x,y) } });
(function(){ (x,y,z) });
(x,y,z);
(function(){ { (x,y,z) } });
(function(){ (a,b,c,d,e,f,g) });
(a,b,c,d,e,f,g);
(function(){ { (a,b,c,d,e,f,g) } });
(function(){ (new Object) });
(new Object);
(function(){ { (new Object) } });
(function(){ (new Object()) });
(new Object());
(function(){ { (new Object()) } });
(function(){ (new Object(42)) });
(new Object(42));
(function(){ { (new Object(42)) } });
(function(){ (new Object(1,2,3)) });
(new Object(1,2,3));
(function(){ { (new Object(1,2,3)) } });
(function(){ (String()) });
(String());
(function(){ { (String()) } });
(function(){ (String(42)) });
(String(42));
(function(){ { (String(42)) } });
(function(){ (String(1,2,3)) });
(String(1,2,3));
(function(){ { (String(1,2,3)) } });
(function(){ [] });
[];
(function(){ { [] } });
(function(){ [1] });
[1];
(function(){ { [1] } });
(function(){ [1,2] });
[1,2];
(function(){ { [1,2] } });
(function(){ [1,2,3] });
[1,2,3];
(function(){ { [1,2,3] } });
(function(){ [1,,2,3] });
[1,,2,3];
(function(){ { [1,,2,3] } });
(function(){ [1,,,2,3] });
[1,,,2,3];
(function(){ { [1,,,2,3] } });
(function(){ [1,,,2,,3] });
[1,,,2,,3];
(function(){ { [1,,,2,,3] } });
(function(){ [1,,,2,,,3] });
[1,,,2,,,3];
(function(){ { [1,,,2,,,3] } });
(function(){ [,1,2,3] });
[,1,2,3];
(function(){ { [,1,2,3] } });
(function(){ [,,1,2,3] });
[,,1,2,3];
(function(){ { [,,1,2,3] } });
(function(){ [,,,1,2,3] });
[,,,1,2,3];
(function(){ { [,,,1,2,3] } });
(function(){ [,,,1,2,3,] });
[,,,1,2,3,];
(function(){ { [,,,1,2,3,] } });
(function(){ [,,,1,2,3,,] });
[,,,1,2,3,,];
(function(){ { [,,,1,2,3,,] } });
(function(){ [,,,1,2,3,,,] });
[,,,1,2,3,,,];
(function(){ { [,,,1,2,3,,,] } });
(function(){ [,,,,,] });
[,,,,,];
(function(){ { [,,,,,] } });
(function(){ ({}) });
({});
(function(){ { ({}) } });
(function(){ ({x:1}) });
({x:1});
(function(){ { ({x:1}) } });
(function(){ ({x:1, y:2}) });
({x:1, y:2});
(function(){ { ({x:1, y:2}) } });
(function(){ ({x:1, y:2, z:3}) });
({x:1, y:2, z:3});
(function(){ { ({x:1, y:2, z:3}) } });
(function(){ ({x:1, 'y':2, z:3}) });
({x:1, 'y':2, z:3});
(function(){ { ({x:1, 'y':2, z:3}) } });
(function(){ ({'x':1, 'y':2, z:3}) });
({'x':1, 'y':2, z:3});
(function(){ { ({'x':1, 'y':2, z:3}) } });
(function(){ ({'x':1, 'y':2, 3:3}) });
({'x':1, 'y':2, 3:3});
(function(){ { ({'x':1, 'y':2, 3:3}) } });
(function(){ 2 + 3 });
2 + 3;
(function(){ { 2 + 3 } });
(function(){ typeof(0?0:a) });
typeof(0?0:a);
(function(){ { typeof(0?0:a) } });
f; if (1) function f(){};
(function(){ throw 42 });
throw 42;
(function(){ { throw 42 } });
(function(){ for (;;) break });
for (;;) break;
(function(){ { for (;;) break } });
(function(){ for (x; y; z) break });
for (x; y; z) break;
(function(){ { for (x; y; z) break } });
(function(){ for (var x; y; z) break });
for (var x; y; z) break;
(function(){ { for (var x; y; z) break } });
(function(){ for (var x = 42; y; z) break });
for (var x = 42; y; z) break;
(function(){ { for (var x = 42; y; z) break } });
(function(){ for (x; ; z) break });
for (x; ; z) break;
(function(){ { for (x; ; z) break } });
(function(){ for (var x; ; z) break });
for (var x; ; z) break;
(function(){ { for (var x; ; z) break } });
(function(){ for (var x = 42; ; z) break });
for (var x = 42; ; z) break;
(function(){ { for (var x = 42; ; z) break } });
(function(){ for (x; y; ) break });
for (x; y; ) break;
(function(){ { for (x; y; ) break } });
(function(){ for (var x; y; ) break });
for (var x; y; ) break;
(function(){ { for (var x; y; ) break } });
(function(){ for (var x = 42; y; ) break });
for (var x = 42; y; ) break;
(function(){ { for (var x = 42; y; ) break } });
(function(){ for (var x in y) break });
for (var x in y) break;
(function(){ { for (var x in y) break } });
(function(){ for (x in y) break });
for (x in y) break;
(function(){ { for (x in y) break } });
(function(){ { } });
{ };
(function(){ { { } } });
(function(){ { throw 1; throw 2; throw 3; } });
{ throw 1; throw 2; throw 3; };
(function(){ { { throw 1; throw 2; throw 3; } } });
(function(){ ; });
;;
(function(){ { ; } });
(function(){ if (foo) throw 42; });
if (foo) throw 42;;
(function(){ { if (foo) throw 42; } });
(function(){ if (foo) throw 42; else true; });
if (foo) throw 42; else true;;
(function(){ { if (foo) throw 42; else true; } });
(function(){ if (foo) { throw 1; throw 2; throw 3; } });
if (foo) { throw 1; throw 2; throw 3; };
(function(){ { if (foo) { throw 1; throw 2; throw 3; } } });
(function(){ if (foo) { throw 1; throw 2; throw 3; } else true; });
if (foo) { throw 1; throw 2; throw 3; } else true;;
(function(){ { if (foo) { throw 1; throw 2; throw 3; } else true; } });
(function(){ foo: for(;;) break foo; });
foo: for(;;) break foo;;
(function(){ { foo: for(;;) break foo; } });
(function(){ foo: for(;;) continue foo; });
foo: for(;;) continue foo;;
(function(){ { foo: for(;;) continue foo; } });
(function(){ with (obj) { } });
with (obj) { };
(function(){ { with (obj) { } } });
(function(){ with (obj) { obj; } });
with (obj) { obj; };
(function(){ { with (obj) { obj; } } });
(function(){ while (foo) { } });
while (foo) { };
(function(){ { while (foo) { } } });
(function(){ while (foo) { foo; } });
while (foo) { foo; };
(function(){ { while (foo) { foo; } } });
(function(){ do { } while (foo); });
do { } while (foo);;
(function(){ { do { } while (foo); } });
(function(){ do { foo; } while (foo) });
do { foo; } while (foo);
(function(){ { do { foo; } while (foo) } });
(function(){ switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; } });
switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; };
(function(){ { switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; } } });
(function(){ switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; case 42: 42; } });
switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; case 42: 42; };
(function(){ { switch (foo) { case 1: 1; break; case 2: 2; break; default: 3; case 42: 42; } } });
(function(){ try { } catch (e) { } });
try { } catch (e) { };
(function(){ { try { } catch (e) { } } });
(function(){ try { } catch (e) { } finally { } });
try { } catch (e) { } finally { };
(function(){ { try { } catch (e) { } finally { } } });
(function(){ try { } finally { } });
try { } finally { };
(function(){ { try { } finally { } } });
(function(){ function f() { function g() { } function g() { } } });
function f() { function g() { } function g() { } };
(function(){ { function f() { function g() { } function g() { } } } });
(function(){ function f() { function g() { } function g() { return 42 } } });
function f() { function g() { } function g() { return 42 } };
(function(){ { function f() { function g() { } function g() { return 42 } } } });
(function(){ function f() { var x = 42; var x = 43; } });
function f() { var x = 42; var x = 43; };
(function(){ { function f() { var x = 42; var x = 43; } } });
(function(){ ({ get x() { return 42 } }) });
({ get x() { return 42 } });
(function(){ { ({ get x() { return 42 } }) } });
(function(){ ({ set x(v) { return 42 } }) });
({ set x(v) { return 42 } });
(function(){ { ({ set x(v) { return 42 } }) } });